-- Add brand_assets column to campaigns (stores logo, images, colors from crawl)
alter table public.campaigns add column if not exists brand_assets jsonb;

-- Add aspect_ratio and placement to ads
alter table public.ads add column if not exists aspect_ratio text;
alter table public.ads add column if not exists placement text;

-- Add ad_copy to campaigns (headline, primary_text, description generated by Claude)
alter table public.campaigns add column if not exists ad_copy jsonb;
